./monga specs/condicionais.spec.monga > specs/condicionais.spec.expected
./monga specs/hexa.spec.monga > specs/hexa.spec.expected
./monga specs/main.spec.monga > specs/main.spec.expected
./monga specs/example.spec.monga > specs/example.spec.expected
./monga specs/string.spec.monga > specs/string.spec.expected
./monga specs/errors/error_invalid_integer.monga > specs/errors/error_invalid_integer.expected
./monga specs/errors/error_invalid_hexa.monga > specs/errors/error_invalid_hexa.expected
./monga specs/errors/error_invalid_float.monga > specs/errors/error_invalid_float.expected
./monga specs/errors/error_invalid_string.monga > specs/errors/error_invalid_string.expected
