./monga specs/basic.spec.monga > specs/basic.spec.expected
./monga specs/condicionais.spec.monga > specs/condicionais.spec.expected
./monga specs/numbers.spec.monga > specs/numbers.spec.expected
./monga specs/main.spec.monga > specs/main.spec.expected
./monga specs/example.spec.monga > specs/example.spec.expected
./monga specs/string.spec.monga > specs/string.spec.expected
./monga specs/errors/error_invalid_integer.monga > specs/errors/error_invalid_integer.expected
./monga specs/errors/error_invalid_hexa.monga > specs/errors/error_invalid_hexa.expected
./monga specs/errors/error_invalid_float.monga > specs/errors/error_invalid_float.expected
./monga specs/errors/error_invalid_string.monga > specs/errors/error_invalid_string.expected
./monga specs/errors/error_invalid_string_long.monga > specs/errors/error_invalid_string_long.expected
./monga specs/errors/error_invalid_bloco.monga > specs/errors/error_invalid_bloco.expected
./monga specs/declaracoes.spec.monga > specs/declaracoes.spec.expected
./monga specs/blocos.spec.monga > specs/blocos.spec.expected
./monga specs/comandos.spec.monga > specs/comandos.spec.expected
